version: '3'
services:
  mysql:
    image: mariadb:latest
    volumes:
        - /data/docker/volumes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=888888
      - MYSQL_DATABASE=app
    restart: on-failure
    networks:
      - GOLANG

  redis:
    image: redis:3.2.11
    expose: 
      - 6379
    ports:
     - "${REDIS_PORT}:6379"
    volumes:
      - /data/docker/volumes/redis:/data
    restart: on-failure
    networks:
      - GOLANG

  go:
    build:
      context: ./golang
    depends_on:
      - mysql
      - redis
    restart: on-failure
    ports:
      - "${GO_PORT}:80"
    volumes:
      - /data/docker/volumes/golang/app:/go/src/app
    networks:
      - GOLANG

networks:
    GOLANG:${NETWORK_NAME}

