version: '3'

services:
    nginx:
        build:
            context: ./nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ${VOLUME_ROOT}/nginx/logs:/logs
            - ${VOLUME_ROOT}/nginx/data:/data
        depends_on:
            - php-fpm-7
        networks:
            - LEMP

    redis:
        build:
            context: ./redis
        volumes:
            - ${VOLUME_ROOT}/redis/logs:/logs
            - ${VOLUME_ROOT}/redis/data:/data
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - LEMP

    mariaDB:
        image: mariadb:latest
        volumes:
            - ${VOLUME_ROOT}/mariadb:/var/lib/mysql:rw
        ports:
            - "${MARIADB_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=888888
            - MYSQL_DATABASE=app 
            - MYSQL_USER=appuser
            - MYSQL_PASSWORD=123456
        networks:
            - LEMP    

    php-fpm-7:
        build:
            context: ./php/php7
        volumes:
            - ${VOLUME_ROOT}/php/data:/data
            - ${VOLUME_ROOT}/php/logs:/logs
        depends_on:
            - mariaDB
            - redis
        networks:
            - LEMP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariaDB
        depends_on:
            - mariaDB
        networks:
            - LEMP

networks:
    LEMP:
      external:
        name: ${NETWORK_NAME}
